services:
  db:
    image: postgres
    restart: always
    ports:
      - '5434:5432'
    environment:
      POSTGRES_PASSWORD: when_to_process

  graphite:
    image: graphiteapp/graphite-statsd
    ports:
      - 80:80
      - 8080:8080
      - 8125:8125
      - 8125:8125/udp

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"

